language: java
install: true
sudo: true

jdk:
  - oraclejdk11

os:
  - linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: print
      script: echo $signingKey
    - stage: build
      script: ./gradlew build --info
    - stage: deploy
      if: branch = master
      script: ./gradlew publishAllPublicationsToOssrhRepository --debug


notifications:
  slack:
    rooms:
      - overlooking6083:Lp2WgrOh00dRH5MOhbJ2Jt4H#overlib-dev
    on_success: change # default: always
    on_failure: always # default: always